version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: adonis_sql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Changez cela en fonction de vos besoins
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3310:3306'
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  mysqldb:
