version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: adonis_sql_container
    environment:
      MYSQL_ROOT_PASSWORD: root # Changez cela en fonction de vos besoins
      MYSQL_DATABASE: adonis_todos
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3310:3306'
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  mysqldb:
